name: Backend
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  test:
    name: Test

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: backend

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      -
        uses: actions/checkout@v3
      -
        name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: 18
      -
        name: pnpm install
        run: npm install -g pnpm
      -
        run: pnpm install --frozen-lockfile
      -
        run: pnpm test

  build:
    name: Build docker container

    needs: [test]
    runs-on: ubuntu-latest
    
    steps:
      -
        uses: actions/checkout@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to GitHub Container Registry
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Build Docker image (and push on main)
        uses: docker/build-push-action@v4.0.0
        with:
          context: ./backend
          push: ${{ github.ref == 'refs/heads/main' }}
          tags: ghcr.io/cthit/games-backend:latest
